import Head from 'next/head'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>devcriollo site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>
            <code>jhonny site</code>
          </p>
        </div>
      </main>
    </>
  )
}
